# Generated by Django 5.0.6 on 2024-07-05 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_organizacion_horario_atencion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicaciones',
            old_name='autor',
            new_name='autor_usuario',
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='autor_organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_organizacion', to='api_app.organizacion'),
        ),
    ]
