# Generated by Django 5.0.6 on 2024-07-05 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_alter_publicaciones_autor_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='propietario',
        ),
        migrations.AddField(
            model_name='animal',
            name='propietario_organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animales_propios', to='api_app.organizacion'),
        ),
        migrations.AddField(
            model_name='animal',
            name='propietario_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animales_propios', to=settings.AUTH_USER_MODEL),
        ),
    ]
