# Generated by Django 5.0.6 on 2024-07-05 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_adopcion_comunidad_alter_adopcion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcion',
            name='comunidad',
        ),
        migrations.RemoveField(
            model_name='adopcion',
            name='organizacion',
        ),
        migrations.RemoveField(
            model_name='adopcion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='adopcion',
            name='adoptante_organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adopciones_realizadas', to='api_app.organizacion'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='adoptante_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adopciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
