# Generated by Django 5.0.6 on 2024-07-05 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_remove_adopcion_comunidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_programados', to='api_app.organizacion'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('JornadaVacunacion', 'Jornada de Vacunación'), ('CampañaEsterilizacion', 'Campaña de Esterilización'), ('CharlaEducativa', 'Charla Educativa')], max_length=50),
        ),
    ]
